language: node_js
sudo: false
node_js:
- node
install:
- npm install
script:
- npm run-script ci
cache:
  directories:
  - node_modules
env:
  global:
    secure: fFmUNr2JQKBYL9T5iQWeJhmr56e7B9BfvxPxBC6UcvMM9ZY2jr2joMkm8siTDqVDbVj0dOqqgCNfcMo5/nAUe1YZfgcWOF2lsYUiB5U9FyQVIwbWeO7HgMzdvAFyRWt/pc4jiqfRIcYNU7w88E20Zmt9Qo4VGn1DZ8LFa+EmRj8RqLaWvFA0P3K/1947IOIg42INHMLPAtF/O/9KIgPdu/BGgrNbq1TN+aJhCxXz9+P9i2aFT4p/SxEjFdVPCxbaLcIi4iVQYzD47aqY7Y8Bmxb6NRDd6PxWlbepALR4Jj6OOWVdw58LmCUbxt5nDiGH18vy3wmSDorY8Wjb9RBDzDO+D/MqcajNc4oiX4kOjeoGcEbgfkqWWjYOg694QiGj1Xz12Ll4LnCfMo+0ILXRaBSso40+gJLvxO/EG3TDv5bSfFVNhDvOy0M6sm+bcMXWANTQwGzRhb0Ij+caDrETX0V5N9GNZ5WP+wFOhIor3O6OF8fOeJhgYyZBMMIus59dXeiMMN4fZ44HU9QZjCWh6zYHh8Aecwc/f8yObovzgRXopHARWCY5zX3YZ0Ty+/VnXOFudTGNT4MnIDK7gFHSQF94XCKPwADEM03U+znEReO+hp+ykw3/f35H9Z5CMm1M3T0sqyscolPKVSJvVSOP9iBVDi6vhKoQr3bD5oRW4Ss=
