language: node_js
sudo: false
node_js:
- node
install:
- npm install
script:
- npm run-script ci
cache:
  directories:
  - node_modules
env:
  global:
    secure: fFmUNr2JQKBYL9T5iQWeJhmr56e7B9BfvxPxBC6UcvMM9ZY2jr2joMkm8siTDqVDbVj0dOqqgCNfcMo5/nAUe1YZfgcWOF2lsYUiB5U9FyQVIwbWeO7HgMzdvAFyRWt/pc4jiqfRIcYNU7w88E20Zmt9Qo4VGn1DZ8LFa+EmRj8RqLaWvFA0P3K/1947IOIg42INHMLPAtF/O/9KIgPdu/BGgrNbq1TN+aJhCxXz9+P9i2aFT4p/SxEjFdVPCxbaLcIi4iVQYzD47aqY7Y8Bmxb6NRDd6PxWlbepALR4Jj6OOWVdw58LmCUbxt5nDiGH18vy3wmSDorY8Wjb9RBDzDO+D/MqcajNc4oiX4kOjeoGcEbgfkqWWjYOg694QiGj1Xz12Ll4LnCfMo+0ILXRaBSso40+gJLvxO/EG3TDv5bSfFVNhDvOy0M6sm+bcMXWANTQwGzRhb0Ij+caDrETX0V5N9GNZ5WP+wFOhIor3O6OF8fOeJhgYyZBMMIus59dXeiMMN4fZ44HU9QZjCWh6zYHh8Aecwc/f8yObovzgRXopHARWCY5zX3YZ0Ty+/VnXOFudTGNT4MnIDK7gFHSQF94XCKPwADEM03U+znEReO+hp+ykw3/f35H9Z5CMm1M3T0sqyscolPKVSJvVSOP9iBVDi6vhKoQr3bD5oRW4Ss=
notifications:
  slack:
    secure: EGbRD3h9dU7izJrKBoPZt02ll9UhCBSxsIAxtIgLC45d5OnuX61FxvcUwYCVEMIRJaxxOvq10K7myTmbZcz3qQV+qkNROsYh+agmlrA9Bm6fkV2fhsoQPct92QVL9c04j+RMLCmw6wQlRRktWRXiRn3Td++vaPNcngV80kjplrkEX6qq6OUQgTL71KWrdPW2wZpqNlOy25T+0iVcoOFn1DsrfYiwQ6dXbkCM34nDM8YxR131Ce6l8+J0XoeyAOvYIHMtOwaNieUD21Rhh0GdZ3ZYLRClv/XzLiSDfahpRibsKmc/pk5GTnozkMyxzpQU1SWws172pxQvhcxIFKWe/MOYIAlVfoLyaXaXaUe0JFxv8YV8kw9+HVXinFrHlrDzo88y8PqnXnYW/D+86X+Uvqcqdnn6aW9KELE0GdVyAs470B2Re/VYtwQKMYHLxU0HK9Vd9qrUvxUNWmOVtgqRHfYW89WlLHA5hNzhYufAEgRhi7nP2TVqQdXXO5ySB4yxwsypDIWoLQMJVKZJvm8tR0/WmfVLdZoFxUehzDCxsQvpPHzNOZYhJL11PmeMr9/4N0MQyIkIE4T+xyf724JlASMLyFKewLJC4EPdNsB68RAceugcGkGu9HvJtUzs6szsko6v7voTJc3gz2H6GVfkP9DTQN3qBWYCHYrr3gAoWhU=
